/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as OrderRouteImport } from './routes/order'
import { Route as PolicyRouteImport } from './routes/policy'
import { Route as QnaRouteImport } from './routes/qna'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as AuthenticatedBalanceRouteImport } from './routes/_authenticated/balance'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedOrdersRouteImport } from './routes/_authenticated/orders'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedResellerApiRouteImport } from './routes/_authenticated/reseller-api'
import { Route as AuthenticatedAddFundsIndexRouteImport } from './routes/_authenticated/add-funds.index'
import { Route as AuthenticatedAddFundsHistoryRouteImport } from './routes/_authenticated/add-funds.history'
import { Route as AuthenticatedServicePlatformRouteImport } from './routes/_authenticated/service.$platform'
import { Route as ApiPublicV2RouteImport } from './routes/api/public/v2'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderRoute = OrderRouteImport.update({
  id: '/order',
  path: '/order',
  getParentRoute: () => rootRouteImport,
} as any)
const PolicyRoute = PolicyRouteImport.update({
  id: '/policy',
  path: '/policy',
  getParentRoute: () => rootRouteImport,
} as any)
const QnaRoute = QnaRouteImport.update({
  id: '/qna',
  path: '/qna',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedBalanceRoute = AuthenticatedBalanceRouteImport.update({
  id: '/balance',
  path: '/balance',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOrdersRoute = AuthenticatedOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedResellerApiRoute =
  AuthenticatedResellerApiRouteImport.update({
    id: '/reseller-api',
    path: '/reseller-api',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAddFundsIndexRoute =
  AuthenticatedAddFundsIndexRouteImport.update({
    id: '/add-funds/',
    path: '/add-funds/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAddFundsHistoryRoute =
  AuthenticatedAddFundsHistoryRouteImport.update({
    id: '/add-funds/history',
    path: '/add-funds/history',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedServicePlatformRoute =
  AuthenticatedServicePlatformRouteImport.update({
    id: '/service/$platform',
    path: '/service/$platform',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicV2Route = ApiPublicV2RouteImport.update({
  id: '/api/public/v2',
  path: '/api/public/v2',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/order': typeof OrderRoute
  '/policy': typeof PolicyRoute
  '/qna': typeof QnaRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/balance': typeof AuthenticatedBalanceRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/orders': typeof AuthenticatedOrdersRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/reseller-api': typeof AuthenticatedResellerApiRoute
  '/add-funds/history': typeof AuthenticatedAddFundsHistoryRoute
  '/service/$platform': typeof AuthenticatedServicePlatformRoute
  '/api/public/v2': typeof ApiPublicV2Route
  '/add-funds/': typeof AuthenticatedAddFundsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/order': typeof OrderRoute
  '/policy': typeof PolicyRoute
  '/qna': typeof QnaRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/balance': typeof AuthenticatedBalanceRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/orders': typeof AuthenticatedOrdersRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/reseller-api': typeof AuthenticatedResellerApiRoute
  '/add-funds/history': typeof AuthenticatedAddFundsHistoryRoute
  '/service/$platform': typeof AuthenticatedServicePlatformRoute
  '/api/public/v2': typeof ApiPublicV2Route
  '/add-funds': typeof AuthenticatedAddFundsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/order': typeof OrderRoute
  '/policy': typeof PolicyRoute
  '/qna': typeof QnaRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/_authenticated/balance': typeof AuthenticatedBalanceRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/orders': typeof AuthenticatedOrdersRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/reseller-api': typeof AuthenticatedResellerApiRoute
  '/_authenticated/add-funds/history': typeof AuthenticatedAddFundsHistoryRoute
  '/_authenticated/service/$platform': typeof AuthenticatedServicePlatformRoute
  '/api/public/v2': typeof ApiPublicV2Route
  '/_authenticated/add-funds/': typeof AuthenticatedAddFundsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/forgot-password'
    | '/order'
    | '/policy'
    | '/qna'
    | '/reset-password'
    | '/sign-in'
    | '/sign-up'
    | '/balance'
    | '/dashboard'
    | '/orders'
    | '/profile'
    | '/reseller-api'
    | '/add-funds/history'
    | '/service/$platform'
    | '/api/public/v2'
    | '/add-funds/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/forgot-password'
    | '/order'
    | '/policy'
    | '/qna'
    | '/reset-password'
    | '/sign-in'
    | '/sign-up'
    | '/balance'
    | '/dashboard'
    | '/orders'
    | '/profile'
    | '/reseller-api'
    | '/add-funds/history'
    | '/service/$platform'
    | '/api/public/v2'
    | '/add-funds'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/admin'
    | '/forgot-password'
    | '/order'
    | '/policy'
    | '/qna'
    | '/reset-password'
    | '/sign-in'
    | '/sign-up'
    | '/_authenticated/balance'
    | '/_authenticated/dashboard'
    | '/_authenticated/orders'
    | '/_authenticated/profile'
    | '/_authenticated/reseller-api'
    | '/_authenticated/add-funds/history'
    | '/_authenticated/service/$platform'
    | '/api/public/v2'
    | '/_authenticated/add-funds/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  OrderRoute: typeof OrderRoute
  PolicyRoute: typeof PolicyRoute
  QnaRoute: typeof QnaRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignInRoute: typeof SignInRoute
  SignUpRoute: typeof SignUpRoute
  ApiPublicV2Route: typeof ApiPublicV2Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order': {
      id: '/order'
      path: '/order'
      fullPath: '/order'
      preLoaderRoute: typeof OrderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/policy': {
      id: '/policy'
      path: '/policy'
      fullPath: '/policy'
      preLoaderRoute: typeof PolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qna': {
      id: '/qna'
      path: '/qna'
      fullPath: '/qna'
      preLoaderRoute: typeof QnaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/balance': {
      id: '/_authenticated/balance'
      path: '/balance'
      fullPath: '/balance'
      preLoaderRoute: typeof AuthenticatedBalanceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/orders': {
      id: '/_authenticated/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof AuthenticatedOrdersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reseller-api': {
      id: '/_authenticated/reseller-api'
      path: '/reseller-api'
      fullPath: '/reseller-api'
      preLoaderRoute: typeof AuthenticatedResellerApiRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/add-funds/': {
      id: '/_authenticated/add-funds/'
      path: '/add-funds'
      fullPath: '/add-funds/'
      preLoaderRoute: typeof AuthenticatedAddFundsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/add-funds/history': {
      id: '/_authenticated/add-funds/history'
      path: '/add-funds/history'
      fullPath: '/add-funds/history'
      preLoaderRoute: typeof AuthenticatedAddFundsHistoryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/service/$platform': {
      id: '/_authenticated/service/$platform'
      path: '/service/$platform'
      fullPath: '/service/$platform'
      preLoaderRoute: typeof AuthenticatedServicePlatformRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/v2': {
      id: '/api/public/v2'
      path: '/api/public/v2'
      fullPath: '/api/public/v2'
      preLoaderRoute: typeof ApiPublicV2RouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedBalanceRoute: typeof AuthenticatedBalanceRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedOrdersRoute: typeof AuthenticatedOrdersRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedResellerApiRoute: typeof AuthenticatedResellerApiRoute
  AuthenticatedAddFundsHistoryRoute: typeof AuthenticatedAddFundsHistoryRoute
  AuthenticatedServicePlatformRoute: typeof AuthenticatedServicePlatformRoute
  AuthenticatedAddFundsIndexRoute: typeof AuthenticatedAddFundsIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedBalanceRoute: AuthenticatedBalanceRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedOrdersRoute: AuthenticatedOrdersRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedResellerApiRoute: AuthenticatedResellerApiRoute,
  AuthenticatedAddFundsHistoryRoute: AuthenticatedAddFundsHistoryRoute,
  AuthenticatedServicePlatformRoute: AuthenticatedServicePlatformRoute,
  AuthenticatedAddFundsIndexRoute: AuthenticatedAddFundsIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  OrderRoute: OrderRoute,
  PolicyRoute: PolicyRoute,
  QnaRoute: QnaRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignInRoute: SignInRoute,
  SignUpRoute: SignUpRoute,
  ApiPublicV2Route: ApiPublicV2Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
